### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [quic-go/webtransport-go#72]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by marten-seemann** [comment]
Done.

**Comment by marten-seemann** [comment]
Having not received a vulnerability report, and seeing the exact same message spammed to [almost 800](https://github.com/search?q=%22Reporting+a+vulnerability%22+is%3Aissue+author%3Aigibek&type=issues&p=1) repos, I'm suspecting that this is spam, or, best case, an irrelevant vulnerability in a dependency.

Happy to be convinced otherwise, but this is where the available information is pointing right now.
